=pod

=head1 NAME

MooseX::NestedAttributesConstructor - Create attributes from a nested data structure

=head1 OVERVIEW

  package Address
  use Moose;

  has street => ( is => 'rw' );
  has city   => ( is => 'rw' );
  # ...

  package Person;
  use Moose;

  has name      => ( is => 'rw' );
  has addresses => ( is     => 'rw',
    		     isa    => 'ArrayRef[Address]',
    		     traits => ['NestedAttribute'] );
  # ...

  package main;
  use Person;

  my $p = Person->new(name      => 'sshaw',
    		      addresses => [
    			{ city => 'LA' },
    			{ city => 'Da Bay' },
			{ city => 'Even São José' }
     		      ]);

  say $_->city for @{$p->addresses};

=head1 WARNING

This is the first Moose I've cooked. 

=head1 DESCRIPTION

This module sets attributes from a nested data structure passed to the constructor of your Moose object. 
The appropriate types will be created. Just add the C<NestedAttrubute> trait to attributes with a custom 
or parameterized type.

=head1 AUTHOR

Skye Shaw (sshaw AT lucas.cis.temple.edu) 

=head1 SEE ALSO

L<MooseX::StrictConstructor>

=head1 COPYRIGHT

Copyright (c) 2012 Skye Shaw.

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.
